name: Deploy project workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable.yml
  test:
    needs: build
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Lint and test
        run: |
          npm run test -- --watch=false
          npm run lint
  deploy:
    needs: [build, test]
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH connection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/my-angular-app

            # Use nvm to install and use Node.js v23.2.0 on the server
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load nvm
            nvm install v23.8.0
            nvm use v23.8.0

            git checkout main
            git reset --hard HEAD
            git pull
            node -v
            npm -v
            npm ci
            npm run build

            rm -r browser 
            mkdir browser
            mv ./dist/kujacic-cicd/browser/* ./browser
            exit
