name: Deploy project workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Lint and test
        run: |
          npm run test -- --watch=false
          npm run lint
  deploy:
    needs: test
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .angular/cache
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build
      - name: Execute SSH connection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/my-angular-app

            # Use nvm to install and use Node.js v23.2.0 on the server
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Load nvm
            nvm install v23.8.0
            nvm use v23.8.0

            git checkout main
            git reset --hard HEAD
            git pull
            node -v
            npm -v
            npm ci
            npm run build

            rm -r browser 
            mkdir browser
            mv ./dist/kujacic-cicd/browser/* ./browser
            exit
